Design details
needsguidance/Simple-GUI pull request #4
Opened 2019-08-23 17:22 UTC by cfboy

Added new buttons (Change Color and Arrow speed). Move buttons (new layout). Add clear text for center label when clear button is pressed.

2019-08-23 22:11 UTC, alejoreyes96 submitted a review, later dismissed
Works good

2019-08-25 05:42 UTC, noelvalentin submitted a review, later dismissed

2019-08-25 14:50 UTC, ChristianPerez34 requested changes

2019-08-25 14:50 UTC, ChristianPerez34 commented on requirements.txt
>  kivy_deps.gstreamer
Cambia el underscore por un dash!

2019-08-25 15:20 UTC, cfboy commented on requirements.txt
>  kivy_deps.gstreamer
Got it.

2019-08-25 16:12 UTC, ChristianPerez34 approved these changes

2019-08-25 16:14 UTC, alejoreyes96 approved these changes

2019-08-25 16:16 UTC, noelvalentin approved these changes

2019-08-25 16:17 UTC, merged